services:
  - type: web
    name: nino-honey-store
    env: node
    buildCommand: npm install
    startCommand: node server.js
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: PHONEPE_MERCHANT_ID
        sync: false
      - key: PHONEPE_SALT_KEY
        sync: false
      - key: PHONEPE_SALT_INDEX
        value: 1
      - key: PHONEPE_ENV
        value: UAT
      - key: SHIPROCKET_EMAIL
        sync: false
      - key: SHIPROCKET_PASSWORD
        sync: false
